"""Add first_name, surname, department, phone_number to User

Revision ID: 0b1a7cb7755b
Revises: d13324638238
Create Date: 2026-04-02 13:23:51.866978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1a7cb7755b'
down_revision = 'd13324638238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('surname')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
