"""add career fields to service requests

Revision ID: bb8765a3f3c4
Revises: 0b1a7cb7755b
Create Date: 2026-04-02 13:32:49.494575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8765a3f3c4'
down_revision = '0b1a7cb7755b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degree_level', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('past_degree', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_column('languages')
        batch_op.drop_column('experience')
        batch_op.drop_column('past_degree')
        batch_op.drop_column('degree_level')

    # ### end Alembic commands ###
